### ISSUE TITLE
Datatable custom sort and default sort

### ISSUE THREAD

**Issue by elmartino** [Teradata/covalent#1127] opened 2018-02-24 21:51 UTC
Hi,

I'm able to use custom sort when having a datatable date column. It's working good with code:

`if (this.sortBy.toLowerCase() === 'created_at') {
                const datea = new Date(a.created_at);
                const dateb = new Date(b.created_at);
                return <any>dateb - <any>datea;
}`

Now i have a default sort: sortBy: string = 'created_at';

The code above is not applied on page load, but only on manual sort. Anyone knows how to apply the sort logic also on page load?

Thanks!

**Comment by jeremysmartt** [comment] 2018-09-06 19:08
closing as duplicate of #461

**Closed by jeremysmartt** 2018-09-06 19:08 UTC
Labels: Close Possible
