### ISSUE TITLE
Black td-layout-nav logo in IE Edge

### ISSUE THREAD

**Issue by ericis** [Teradata/covalent#435] opened 2017-03-21 19:14 UTC
#### Bug Report

The SVG icon at the top of this website appears black in IE Edge, but color in other browsers:
http://aa-tech-talk.azurewebsites.net/welcome

Can you tell if this is an issue with styling vs. the SVG itself? I'm having difficulting navigating the hierarchy of both Covalent and Material directives and styles. Oddly, it appears to work well in IE11 and also works in Chrome and FF. I thought it was strange that Edge did not display it correctly and IE11 did. I verified Emulation was off in dev tools.

Using `MdIconRegistry`...
`this.registerIcon('logo-aa-tail', '/logos/aa-tail.svg');`
`<td-layout-nav logo="assets:logo-aa-tail">`

I realize that `MdIconRegistry` is from Material, but it appeared that the rendering was occurring in Covalent's `td-layout-nav` tag.

#### What is the expected behavior?

Logo appears in color with gradients applied.

#### What is the motivation / use case for changing the behavior?

Consistency in presentation.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

`Windows 10 Enterprise`

```
@angular/cli: 1.0.0-rc.1
node: 6.9.4
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
```

**Comment by rafaelcgdf** [comment] 2017-03-24 17:04
Probably my issue is not related to this specific but it is with SVG, and I don't know if the problem is with Angular Material or Cavalent itself..

Back last week when I added Covalent the logos were being displayed just fine, but since yesterday they don't appear at all, has anybody had this issue before? It's like the SVG I'm passing is blank.

I know I'm using MdIconRegistry correctly because if I misspell the string used for the SVG, the application just blows up.

**Comment by emoralesb05** [comment] 2017-10-11 17:06
Closing since there hasnt been any activity, if the problem is still there please re-open.

**Closed by emoralesb05** 2017-10-11 17:06 UTC
