### ISSUE TITLE
td-page-bar behavior at managed list, when the list shrinks

### ISSUE THREAD

**Issue by lincze** [Teradata/covalent#445] opened 2017-03-26 04:35 UTC
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Perhaps a bug, but well may be a misunderstanding on my part.
#### Bug Report
I have a managed list, and added search and td-paging-bar to it. When paging forward, and then issue a search (which shrinks the list total size), the paging bar remains on the page it was before, though it may be over the total size of the hit list, now. e.g. "Row per page: 5    11-9 of 9" (when hit list is of 9 size and I was on the 3rd page on an originally 30 items list).

#### What is the expected behavior?
page-bar should rewind to the 1st, or maxpage, when the total size changes, so that the current page is over it.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
not relevant.

One can reproduce the behavior on the Covalent Quickstart demo, at https://teradata.github.io/covalent-quickstart/#/product/stats paging forward , and then issue a search, e.g. "da".

**Comment by Balasahebraut** [comment] 2017-03-27 10:27
@lincze , you can fix for temporary hack by giving fixed height with scroll true. So page will not get shrink.

**Comment by lincze** [comment] 2017-03-28 13:20
i thought of some simple fix (e.g. a "set total()" method on the total input property which rewinds to the first page if total is less than the pagesize * pagenumber, that emits a change event). but not sure if it were good, i'm a newcomer in the javascript/ui environment, always worked on server side.

**Comment by emoralesb05** [comment] 2017-03-28 14:32
@lincze the problem is that there are cases when the total changes and you dont want to be back at the first page ( e.g. growing logs ).

You can however just call `navigateTo(1)` manually when that happens on your end.

**Comment by lincze** [comment] 2017-03-28 15:08
@emoralesb05 i just thought that it (or anything reasonable, e.g. max pagenum) should be a "factory default" behavior **iff** ```total < pagenum * pagesize``` after shrinking (but can live without it)

**Comment by emoralesb05** [comment] 2017-10-11 17:10
Closing this since users can have control by specifying the page they want to jump to after a search (typically page 1)

**Closed by emoralesb05** 2017-10-11 17:10 UTC
