### ISSUE TITLE
feature: datetime picker (basic functionalities)

### ISSUE THREAD

**Issue by jotatoledo** [Teradata/covalent#849] opened 2017-08-31 19:11 UTC
#### What is the motivation ?

Considering that the material team will most likely start the develop of this feature in the next year, I think it would be a great functionality to add into covalent (in a basic functional form). 

There are definitely a lot of developers out there who would love to see covalent offering this.

##### Expected behavior

Create a new component that adds to the current material datepicker the capability to manipulate time instance variables of a DateTime class (moment, Date or others depending on the supplied DateAdapter implementation).

##### Other information

The issue tracker for material datetime picker can be found [here](https://github.com/angular/material2/issues/5648)

Examples of implementations of this can be found in [primeng](https://www.primefaces.org/primeng/#/calendar) what I would personally suggest as starting point and [ngx-ui](https://swimlane.github.io/ngx-ui/#datetime) (personally dislike the overlay part of it). Both of this implementations dont follow the material spec but hey, its at least something! 😄

**Comment by kyleledbetter** [comment] 2017-08-31 20:09
Hmmm, i wonder if we could just use a separate md-select for Time next to the Datepicker...

**Comment by emoralesb05** [comment] 2017-08-31 22:17
I would like to start barking at this tree for a while and see if we can brainstorm in this thread on how this could be implemented or solved.

**Comment by jotatoledo** [comment] 2017-08-31 22:19
I forgot to point out to [this other implementation](http://code.promactinfo.com/md2/#/datepicker) which matches the material design spec

**Comment by vwchu** [comment] 2017-09-02 04:47
There is another Time picker implementation that matches the Material Design spec, but not written in Angular unfortunately (http://materializecss.com/forms.html#time-picker). However, it could be wrapped in a directive. https://github.com/sherweb/ng2-materialize/issues/170.

P.S.: One issue I have with the implementation mentioned by @jotatoledo and this one, is integrating the theming and colours with @angular/material's.

**Comment by jotatoledo** [comment] 2017-09-03 22:03
Some more resources on this: https://github.com/Imbasoft/ng-imbaDatepicker

**Comment by jeremysmartt** [comment] 2018-08-15 23:26
closing for duplicate of #1167

**Closed by jeremysmartt** 2018-08-15 23:26 UTC
Labels: future, open for debate
