### ISSUE TITLE
[feat] Allow to use color attribute in the td-layout-footer to implement bottom bar

### ISSUE THREAD

**Issue by pdjota** [Teradata/covalent#489] opened 2017-04-06 15:28 UTC
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug

#### Bug
In Material it is expected to have a bottom-nav, the current component in Material is Not started
Currently the td-layout contains a td-layout-footer but the color is not taken into consideration because it creates an intermediate div.td-layout-footer which does not take it into account

  <td-layout-footer color="primary">
    Using Covalent 1.0.0-beta.2 with Angular 2.4.5 and Material 2.0.0-beta.2
  </td-layout-footer>

##### Screenshots or link to CodePen/Plunker/JSfiddle
http://plnkr.co/edit/IFzpb1Nxbu6ZiK4UIWnV?p=preview

#### What is the expected behavior?
Generated div is using the color indicated in the attribute

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Using Covalent 1.0.0-beta.2 with Angular 2.4.5 and Material 2.0.0-beta.2
 
Did this work in previous versions of Angular / Material?
N/A

**Comment by netbka** [comment] 2017-06-07 20:59
Same issue with my project.
Did you find any solution?

**Comment by kyleledbetter** [comment] 2017-06-07 21:35
This is an enhancement not a bug since we intended it to use the light or dark theme original but it will be nice to add the color input feature

**Comment by emoralesb05** [comment] 2017-07-11 14:15
This has already been merged

**Closed by emoralesb05** 2017-07-11 14:15 UTC
Labels: enhancement
