### ISSUE TITLE
DataTable - Search and Pagination- Issued

### ISSUE THREAD

**Issue by leerenold** [Teradata/covalent#617] opened 2017-05-23 18:10 UTC
Search content in datatable from second page or after returning "no results to display".

If you search from first page it is working, but user can search content from any page he/she is in.

Example from documentation:
Data Table with components
Paging Bar / Search Box / Sortable components

Steps to reproduce : 
1. Go to second page in datatable. It has "donut" Dessert.
2. Now search "donut". "No results to display".

Note:
I can fix displaying search result in the filter method, but pagination not working properly as I dont have access to pagingEvent during search.

Thanks.
![dt_secondpage](https://cloud.githubusercontent.com/assets/17286159/26369038/b775955a-3fb0-11e7-94c3-a84b58ed2cd9.PNG)
![dt_withsearchfilter](https://cloud.githubusercontent.com/assets/17286159/26369045/ba619ae8-3fb0-11e7-9ab5-d6f74ca12d0f.PNG)

**Comment by jotatoledo** [comment] 2017-05-23 18:21
Nice observation. The fix would be most likely

```
 search(searchTerm: string): void {
    this.searchTerm = searchTerm;
    this.currentPage = 1;
    this.filter();
  }
```

**Comment by leerenold** [comment] 2017-05-23 18:54
@jotatoledo 
Thanks for the quick reply.
Ya I tried that fix before. It brings the searched content correctly. But pagination wont work as expected as I dont have access to pagingEvent during search.

Though I use in search()
this.currentPage = 1, this.fromRow = 1;

I can also change in filter(), but anyway i need access to paginEvent of td-paging-bar to work.Correct me if I am wrong.

Thanks.

**Comment by jotatoledo** [comment] 2017-05-23 19:02
Oh yeah! The problem is that the `currentPage `value is correct, but is out of sync with the paginationComponent. A solution would be to store a reference to the`@ViewChild` fot the paginationComponent and then manually set the values

**Comment by lincze** [comment] 2017-05-23 19:13
i think , this is duplicate of #445 - i would prefer to solve it in the framework component (enough common scenario with any kind of filtering). you can fix the behavior by maintaining a reference to the paging viewchild, and relocate the page to the 1st one, whenever the list size (paging total) shrinks to go under your current page.

**Comment by jotatoledo** [comment] 2017-05-23 19:45
Not sure if the issues are really the same. Anyways, the way I implemented this is case, is that every time that the user performs a search, the pagination component will navigate to the first page (the easy aproach), but the correct in my opinion. Perfoming a filtering of entries will alter the state of what the user saw as 1st page, so it would be logic to show it to him immediately after the filtering is done

**Comment by leerenold** [comment] 2017-05-24 15:56
I agree with @lincze , it should be a framework component fix. For time being , used reference to pagingComponent to modify fromRow and page value during search() and page() and return to the page the user left off while clearing search.

Something like this.
@ViewChild(TdPagingBarComponent) pagingComp = TdPagingBarComponent;

**search**(searchTerm: string): void {
        this.searchTerm = searchTerm;
        if(this.searchTerm == ""){
            this.fromRow = this.pagingComp._fromRow = this.prevFromRow;
            this.currentPage = this.pagingComp._page = this.prevCurPage;
        }
        else{
            this.fromRow = this.pagingComp._fromRow = 1;
            this.currentPage = this.pagingComp._page = 1;
        }
        this.filter();
    }

    **page**(pagingEvent: IPageChangeEvent): void {
        if(this.searchTerm != ""){
            this.fromRow = pagingEvent.fromRow;
            this.currentPage = pagingEvent.page;
        }
        else {
            this.fromRow = this.prevFromRow =  pagingEvent.fromRow;
            this.currentPage = this.prevCurPage = pagingEvent.page;
        }
        this.pageSize = pagingEvent.pageSize;
        this.filter();
    }

Thanks.

**Comment by jotatoledo** [comment] 2017-06-04 19:09
close? @emoralesb05

**Comment by emoralesb05** [comment] 2017-10-11 17:48
Closing this since the devs have full control of this behavior

**Closed by emoralesb05** 2017-10-11 17:48 UTC
Labels: bug, docs
