### ISSUE TITLE
Add a support for @angular/material@2.0.0-beta.11

### ISSUE THREAD

**Issue by jega4u** [Teradata/covalent#887] opened 2017-09-25 17:13 UTC
#### Feature Request

```
JEGA1:web jega$ npm install  @angular/material
npm WARN \@angular/cdk@2.0.0-beta.10 requires a peer of @angular/common@^4.3.0 but none was installed.
npm WARN \@angular/compiler-cli@4.4.1 requires a peer of @angular/compiler@4.4.1 but none was installed.
npm WARN \@angular/compiler-cli@4.4.1 requires a peer of @angular/core@4.4.1 but none was installed.
npm WARN \@angular/flex-layout@2.0.0-beta.9 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN \@angular/material@2.0.0-beta.11 requires a peer of @angular/cdk@2.0.0-beta.11 but none was installed.
npm WARN \@angular/material@2.0.0-beta.11 requires a peer of @angular/common@^4.4.3 but none was installed.
npm WARN \@covalent/core@1.0.0-beta.7 requires a peer of @angular/common@^4.3.0 but none was installed.
npm WARN \@covalent/core@1.0.0-beta.7 requires a peer of @angular/forms@^4.3.0 but none was installed.
npm WARN \@covalent/core@1.0.0-beta.7 requires a peer of @angular/http@^4.3.0 but none was installed.
npm WARN \@covalent/core@1.0.0-beta.7 requires a peer of @angular/router@^4.3.0 but none was installed.
npm WARN \@covalent/highlight@1.0.0-beta.7 requires a peer of @angular/common@^4.3.0 but none was installed.
npm WARN \@covalent/markdown@1.0.0-beta.7 requires a peer of @angular/common@^4.3.0 but none was installed.
npm WARN \codelyzer@3.0.1 requires a peer of \@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.

+ \@angular/material@2.0.0-beta.11
updated 1 package in 7.212s


```

**Comment by aciccarello** [comment] 2017-09-25 17:14
Related to #885

**Comment by splurtcake** [comment] 2017-09-28 04:30
Any fix for this?

**Comment by kyleledbetter** [comment] 2017-09-28 14:41
We’ll support beta11 in our next release. Closing since it’s planned and not a bug

**Closed by kyleledbetter** 2017-09-28 14:41 UTC

**Comment by emoralesb05** [comment] 2017-10-03 15:11
https://github.com/Teradata/covalent/pull/890 has been merged, you can start testing if you install the `nightly-build`, and we are gonna release as soon as we do a last set of tests
