### ISSUE TITLE
TD-Dynamic-Forms : not able to create numeric textbox only for integer value (multiple issues)

### ISSUE THREAD

**Issue by Sam89Jha** [Teradata/covalent#562] opened 2017-05-06 15:57 UTC
Bug :
1. I am not able to create textbox which accepts only integer values without decimal. 
2. String/text type parameters should also accept regex as input for custom validation or restriction over input data.
3. dynamic controls are not highlighted invalid even if default value set is invalid.
4. Auto design of controls is not appropriate , should ask for input says how to render controls - columns, rows

**Comment by kyleledbetter** [comment] 2017-05-06 15:59
Two or three of these are feature requests, can you submit different issues and only report bugs as bugs s we can triage? Also include a plunker for bugs pls

**Comment by Sam89Jha** [comment] 2017-05-06 16:01
sure, I'll do that. but what what about the feature requests as they are highly required when we are using mentioned component

**Comment by emoralesb05** [comment] 2017-05-06 16:08
Sure, just open different issues with `feature request` for 1, 2 and 4 (3 tickets). Since they are improvements that can be tackled separately. 😄 

Number 3 seems like a bug, but might require some `steps to reproduce` or a plnkr.

This way we can add them into the road map, and give them priority (or others can help out too)

**Comment by emoralesb05** [comment] 2017-05-07 23:10
Closing this one since the other 4 were creating with the specific issues.

**Closed by emoralesb05** 2017-05-07 23:10 UTC
