### ISSUE TITLE
Button Issue in Stepper with IE11

### ISSUE THREAD

**Issue by Blankinfinity** [Teradata/covalent#597] opened 2017-05-16 08:32 UTC
First off I know that IE11 isn't support but I am hoping someone can help or point me in the right direction to fix this.

#### Bug Report

When using the stepper in IE11 if you click a button (e.g. in the required state step), it momentarily shifts position and then back again. I have managed to fix a few other issues i was having with layouts etc and flex for my project using Covalent but I am stumped with this one. I'm wondering if this has something to do with the ripple effect?

##### Screenshot

![stepper-button](https://cloud.githubusercontent.com/assets/17241078/26096848/791c5e60-3a1a-11e7-85a9-ca665b3fd847.gif)

#### What is the expected behavior?

Button should not move position when clicking it.

#### What is the motivation / use case for changing the behavior?

UI issue, a user of the web app should not see the button moving position it should be fixed.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular 4.1.1
Material 2.0.0-beta.3

**Comment by emoralesb05** [comment] 2017-05-16 13:35
Does it happen when you click on `Cancel` too?..

Trying to figure out if its a stepper state change or the actual click that give that effect.

**Comment by Blankinfinity** [comment] 2017-05-16 13:41
I can confirm it does not happen when the `Cancel` is clicked

**Comment by mcstepp** [comment] 2017-05-16 15:20
I'm working on a lot of IE11 support issues, so I'll take a look at this later today.

**Comment by mcstepp** [comment] 2017-05-16 17:30
Unfortunately, I can't reproduce this locally. @Blankinfinity you mentioned that you've made some other IE11 fixes. If you have a branch on github, I'll pull it down and take a look. Maybe some of the other fixes are breaking the stepper.

![ie11_stepper](https://cloud.githubusercontent.com/assets/7390124/26119616/d3b24df0-3a3b-11e7-9d0c-f8a338830042.gif)

**Comment by Blankinfinity** [comment] 2017-05-16 17:48
@mcstepp I have made changes to a project for the company i work for so sadly i can't put any of that on github, however that gif was recorded from the main covalent website [https://teradata.github.io/covalent/#/components/steps](url) here, so no changes made by myself and that is the behaviour I am seeing.

**Comment by Blankinfinity** [comment] 2017-05-16 17:56
It doesn't appear to be just related to the stepper component either, I just checked other pages with buttons and I also see it happening on [https://teradata.github.io/covalent/#/components/file-upload](url).

![fileupload-button](https://cloud.githubusercontent.com/assets/17241078/26120654/5f295ce8-3a69-11e7-95ef-27a051f96eba.gif)

**Comment by Blankinfinity** [comment] 2017-05-16 18:02
@mcstepp I think this might be a Material problem, if i change from md-raised-button to a flat md-button the issue goes away

**Comment by mcstepp** [comment] 2017-05-16 18:10
Interesting. I still can't reproduce it from the source on IE11. 
![ie11_buttons](https://cloud.githubusercontent.com/assets/7390124/26121174/6672e5aa-3a41-11e7-8095-14c7386fcb62.gif)

**Comment by Blankinfinity** [comment] 2017-05-16 18:16
@mcstepp Just to let you know I am testing on Windows 10s IE11, i have seen subtle differences with behaviour between the version on Windows 7. I have just tried it on a virtual Windows 7 machine and it behaves as expected. God knows what IE11 in Win 10 is doing!

**Comment by mcstepp** [comment] 2017-05-16 18:33
Good point. I was just about to ask you which OS you were using. I was testing on Windows 7 with IE11. I'll grab a Win 10 machine and see if I can apply any fixes. With it being a dependency issue, it may be best to wait until the owner's fix it. In the mean time, I'll check out those links and see if they include other fixes. I saw one for the button in one (the overflow), and also using the flat button as you mentioned earlier. Keeping this on my radar since my application has to support Windows 10 also.

**Comment by Blankinfinity** [comment] 2017-05-16 18:41
Just in case there are any differences between windows 10 versions I have replicated this on 1607 and 1703.

**Comment by mcstepp** [comment] 2017-05-16 19:03
Very interesting. I'm testing now with Windows 10 version 1607 on IE11 (physical, not virtual) and I still can't reproduce it. I'll try it again on a VM.

**Comment by Blankinfinity** [comment] 2017-05-17 05:29
Morning, for now until a fix can be found i've disabled ripple effects using `MD_RIPPLE_GLOBAL_OPTIONS`.

Information on how to use it can be found here [https://github.com/angular/material2/blob/master/src/lib/core/ripple/README.md](url)

This has fixed the issue i was seeing but ideally I would love to have the ripple effects working.

**Comment by Blankinfinity** [comment] 2017-05-17 09:40
@mcstepp I have tried this on my 1607 machine at work today and the issue does not occur (although i could have sworn it did), so looks like it might be a problem in 1703 only

**Comment by kyleledbetter** [comment] 2017-08-24 00:10
Hey folks I'm testing for IE11 fixes and can't reproduce any of these issues. I'm thinking it must have been an upstream fix in Angular Material for the ripple.

Can anyone else test and confirm?

**Comment by Blankinfinity** [comment] 2017-09-03 20:12
@kyleledbetter I'll update to the latest version and check it out to see if it is still a problem and get back to you.

**Comment by emoralesb05** [comment] 2017-10-11 17:40
Closing this since we couldnt replicate it and its not a covalent specific issue

**Closed by emoralesb05** 2017-10-11 17:40 UTC
