### ISSUE TITLE
Search work only in the first page of data table

### ISSUE THREAD

**Issue by jkprad** [Teradata/covalent#1218] opened 2018-08-14 16:33 UTC
Bug:

https://teradata.github.io/covalent/#/components/data-table

In this data-table, go to second or 3rd page of the table and try to search either any name available in any of the pages or name available in the current 2nd or 3rd page.

It gives zero search results. Move back to 1st page and do the same search, verify that it gives correct search result.

example search word: Thaddeus
result while in 2nd page: 0
result while in 1st page: 1

### Do you want to request a *feature* or report a *bug*?
Bug
#### Bug Report

StackBlitz template: https://stackblitz.com/edit/covalent

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by jeremysmartt** [comment] 2018-08-15 00:03
Duplicate of #1202

**Closed by jeremysmartt** 2018-08-15 00:03 UTC
