### ISSUE TITLE
CovalentFileModule missing @NgModule annotation in 1.0.0-rc.3

### ISSUE THREAD

**Issue by galtalmor** [Teradata/covalent#1100] opened 2018-01-23 02:04 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

##### Screenshots or link to CodePen/Plunker/JSfiddle
This is what happens when I run `ng build --prod`. Which worked just fine with `Covalent 1.0.0-rc.1`, but once I upgrade to `Covalent 1.0.0-rc.3` it stops working.
![image](https://user-images.githubusercontent.com/881668/35254313-8866846e-ff9e-11e7-838f-8f55aed0c1c3.png)

#### What is the expected behavior?
Successful build when using CovalentFileModule

#### What is the motivation / use case for changing the behavior?
Successful build when using CovalentFileModule

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 5.2.1
Material 5.1.0
Win 10
Chrome 63

Did this work in previous versions of Angular / Material?
It worked with older version of Covalent (1.0.0-rc.1).
Doesn't work with and version of Angular/Material with Covalent 1.0.0-rc.3

##### Other information
I tried both importing CovalentFileModule from `@covalent/core` and `@covalent/core/file`. Same result.
I suppose someone just removed/forgot to put `@ngModule` by mistake.

**Comment by emoralesb05** [comment] 2018-01-23 04:17
Closing since its a dupe of https://github.com/Teradata/covalent/issues/1099

We will track the progress in the other one

**Closed by emoralesb05** 2018-01-23 04:17 UTC

**Comment by galtalmor** [comment] 2018-01-23 05:35
Sorry, it didn't show up when I searched for the issue. Thanks.
