### ISSUE TITLE
td-chip's handleAdd and handleRemove functions doesn't call when selecting a chip that was already selected

### ISSUE THREAD

**Issue by megetron** [Teradata/covalent#979] opened 2017-11-19 16:46 UTC
#### Bug Report
td-chip's handleAdd and handleRemove functions doesn't call when selecting a chip that was already selected.
#### What is the expected behavior?
I would expect handleAdd and handleRemove to be fire each time the chips is selected.
if a user clicks any ui element, I think you would like to know it. (for statistics reports, or for any other implementations)

#### What is the motivation / use case for changing the behavior?
For example, I would like to set a chip, with how many times it was selected from the dropdown list, something that will be shown like this:
stepper(3 times) expension-panel(1 time)

#### Which version of Angular and Material, and which browser and OS does this issue affect?
angular: 4.4
covalent: 1.0.0-beta.8

**Did this work in previous versions of Angular / Material?**
No.

**Comment by jeremysmartt** [comment] 2018-09-06 18:34
closing as duplicate of #711

**Closed by jeremysmartt** 2018-09-06 18:34 UTC
Labels: Close Possible
