### ISSUE TITLE
feat(dynamic forms): add description to elements

### ISSUE THREAD

**Issue by JulieMarie** [Teradata/covalent#1210] opened 2018-08-13 17:48 UTC
#### Feature Request
Add optional descriptions for elements in the form of either a hint or a hover.

**Comment by jeremysmartt** [comment] 2018-08-13 17:52
Isn't this a duplicate of:
https://github.com/Teradata/covalent/issues/826

**Comment by emoralesb05** [comment] 2018-08-13 17:54
Yup, duplicate

**Closed** 2018-08-13 17:55 UTC
