### ISSUE TITLE
Improve compatibility with Universal

### ISSUE THREAD

**Issue by Gnorro** [Teradata/covalent#822] opened 2017-08-21 12:18 UTC
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
Feature
#### Feature Request

Compatibility for Universal

#### What is the expected behavior?
No error when running app with universal

#### What is the motivation / use case for changing the behavior?
Improving compatibility with Universal

#### Which version of Angular and Material, and which browser and OS does this issue affect?
@angular/cli: 1.3.1
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.5
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

##### Other information
Followed this tutorial:
https://medium.com/@cyrilletuzi/angular-server-side-rendering-in-node-with-express-universal-engine-dce21933ddce
At the end I run:
node server.js

D:\Test\frontend3>node server.js
D:\Test\frontend3\node_modules@covalent\core\dialogs\dialog.component.js:10
import { Component, Directive, ContentChildren, QueryList } from '@angular/core'
;
^^^^^^

SyntaxError: Unexpected token import
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10)
at Module._compile (module.js:533:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object.lwxD (D:\Test\frontend3\dist-server\main.bundle.js:1:952671)

**Comment by aciccarello** [comment] 2017-08-22 15:20
Duplicate of #419

**Comment by emoralesb05** [comment] 2017-08-23 21:39
Yup, this is a dup since we dont technically support universal yet.

**Comment by emoralesb05** [comment] 2017-10-11 18:30
Closing in favor of #419

**Closed by emoralesb05** 2017-10-11 18:30 UTC
