### ISSUE TITLE
ux(dialog): support multiline text in simple dialogs

### ISSUE THREAD

**Issue by quanterion** [Teradata/covalent#791] opened 2017-07-26 13:26 UTC
Currently if you pass multiline string to openAlert()

```
let info = `Model statistics: 
Objects: ${objCount}
Meshes: ${meshCount}
Triangles: ${triCount}`;
    this.dialogService.openAlert({ message: info });
```

Simple Dialogs display all message on a single line. But native dialogs displays the example message on 4 lines. Is it possible to align Teradata dialogs behavior with native?

**Comment by jeremysmartt** [comment] 2018-09-06 19:07
clsoing as duplicate of #713

**Closed by jeremysmartt** 2018-09-06 19:07 UTC
Labels: Close Possible, enhancement, needs discussion
