### ISSUE TITLE
Feature Request - Data Table: Fixed Header when scrolling

### ISSUE THREAD

**Issue by ishatd** [Teradata/covalent#494] opened 2017-04-10 15:18 UTC
Need to have the option to have fixed headers on the data table so that they're visible when scrolling through rows.

**Comment by kyleledbetter** [comment] 2017-04-12 15:40
Playing around w/ an idea here: http://plnkr.co/edit/f8az0wGbhWsgCd0YnUI8?p=preview

I'm just using the flex layout to let the table rows fill the screen and keep the table headers and pagination "stuck" without using complex  javascript positioning

![flex-table](https://cloud.githubusercontent.com/assets/867883/24966357/8f130996-1f5b-11e7-857c-678895114a8a.gif)

Obviously this will face challenges if there are more items in the page than a table, just wanted to test

**Comment by kyleledbetter** [comment] 2017-04-12 15:41
Also looking around the internet for existing solutions, here's a blog and repo for a sticky ng2 directive:

https://medium.com/@MikkelDamm/sticky-header-in-angular2-90364eba81d9

https://github.com/mikkeldamm/angular2-playground/tree/master/app

**Comment by kyleledbetter** [comment] 2017-04-12 15:42
This sticky directive has a nice demo https://rawgit.com/ng2-ui/ng2-sticky/master/app/index.html

**Comment by jraadt** [comment] 2017-04-18 02:38
Seems like a duplicate of #341 

In AngularJS projects I've used md-data-table (https://github.com/daniel-nagy/md-data-table) and have a pull request on fixed-table-header (https://github.com/daniel-nagy/fixed-table-header) to use $mdSticky from Material 1.  @kyleledbetter , you may want to look at fixed-table-header for another idea on how to implement.

**Comment by kyleledbetter** [comment] 2017-04-21 16:17
thx @jraadt i've seen the `fixed-table-header` before and it's probably the most well done example for our use case, but fixed headers for in-page content are always such a janky double-scrollbar-inducing user experience. If a table truly has 100% width and height in a page I'm all for sticky headers and pagination, but we're going to keep debating this one

**Comment by jraadt** [comment] 2017-05-24 14:31
@kyleledbetter I completely agree with the janky double-scrollbar experience.  I never like to make the inside content of the table be scrollable with a fixed height on the header.  Instead I'd recommend you keep the scroll with the page/container or whatever outside-the-table element currently is scrollable.  It's just like having a long table on the scrollable page, but when you start scrolling down on the page when the header would normally disappear, it sticks to the top of the page until the entire table has scrolled past.  Does that make sense?  Keep the 1 scroll on the page (or outer container) and don't scroll inside the table.

**Comment by emoralesb05** [comment] 2017-06-15 21:55
This is currently in the testing and internal usage phase since it goes hand in hand with virtual scrolling for a better performance.

**Comment by emoralesb05** [comment] 2017-06-16 22:56
Small preview of whats coming

![virtual-scrolling-data-table](https://user-images.githubusercontent.com/5846742/27247325-5122a3d8-52ac-11e7-82f3-e26194841e3c.gif)

**Comment by zanecat** [comment] 2017-08-04 02:59
@emoralesb05 exciting, and it's in beta6 now?

**Comment by rasoulMrz** [comment] 2017-09-06 10:31
See link below.
https://stackoverflow.com/questions/43455230/angular-material-fixed-table-header

**Comment by kyleledbetter** [comment] 2017-09-07 11:42
We're about to merge this feature for the next release https://github.com/Teradata/covalent/pull/859

**Comment by zanecat** [comment] 2017-09-07 13:46
@kyleledbetter thx very much

**Closed** 2017-09-08 22:00 UTC
Labels: feature, teradata
