### ISSUE TITLE
tdMessage component is duplicated with *ngIf

### ISSUE THREAD

**Issue by jean3978** [Teradata/covalent#987] opened 2017-11-21 21:46 UTC
### Do you want to request a *feature* or report a *bug*?

bug

#### Bug Report

Steps to reproduce

1.  Use a td-message inside a <div *ngIf="condition">
2.  Change the condition result multiples time

##### Screenshots or link to CodePen/Plunker/JSfiddle
![bug](https://user-images.githubusercontent.com/5321541/33098351-196bdc92-cedb-11e7-973e-afd0e33997fe.gif)

see this plunker:  https://plnkr.co/edit/6NRQD9KQjluwEtdrkTbe?p=preview

#### What is the expected behavior?

The box should not be duplicated.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Same as in the plunker: covalent@1.0.0-rc0.

**Comment by aciccarello** [comment] 2017-11-21 21:56
Duplicate of #981. Already fixed in #984 :smile:

**Comment by jean3978** [comment] 2017-11-21 21:57
oups, sorry I only looked in open issues

**Comment by emoralesb05** [comment] 2017-11-21 22:33
Yup, this was fixed already and will be available in Rc.1.. you can however use the nightly build for the time being.

**Closed by emoralesb05** 2017-11-21 22:33 UTC
