### ISSUE TITLE
Remove loading screen

### ISSUE THREAD

**Issue by QuantumRich** [Teradata/covalent#124] opened 2016-10-27 22:15 UTC
Big fan of this; using it to prototype much faster.

Is it possible to remove the "Loading Covalent Quickstart" screen that occurs every time I refresh?  It would rapidly increase my development time.

**Comment by kyleledbetter** [comment] 2016-10-27 22:18
closing, duplicate of https://github.com/Teradata/covalent-quickstart/issues/17

**Closed by kyleledbetter** 2016-10-27 22:18 UTC
