### ISSUE TITLE
How to build this project with Webpack?

### ISSUE THREAD

**Issue by ElderJames** [Teradata/covalent#386] opened 2017-02-27 15:35 UTC
Hi,I am grade to find such a great project,but I got many trouble when I want to marge covalent and the [aspnet-core angular2spa](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa) project because I need use covalent with .Net Core.

However,the aspnet-core angular2spa project use webpack to build the angular2 and I try to move the .ts file in  path /src/app of covalent to ClilentApp of  aspnet-core angular2spa .Then I can build the project with webpack but it throw a error : window is not defined, when I run the project.

So I need a true way or a config file to build  covalent with webpack.

thanks!

**Comment by emoralesb05** [comment] 2017-02-27 16:39
I think the problem here isnt webpack, the problem is `server side rendering`. 

Covalent/Material arent fully tested with angular universal yet, so there will be issues when trying to use them that way (because we access the `window` element which doesnt exist in the server).

We are trying to support it soon, but we have other priorities first like `a11y`, `i18n` and performance before tackling `angular universal` full support.

**Comment by ElderJames** [comment] 2017-02-27 17:16
Thanks for your answer!

So could I remove the Covalent/Material module until it support angular universal ?

**Comment by emoralesb05** [comment] 2017-02-27 17:23
Yeah, you would need to do that for now, since material also has issues with angular universal at the moment.

**Comment by CamiloTerevinto** [comment] 2017-09-08 15:49
Is there any update on this? It's been some months since the last comment.

**Comment by aciccarello** [comment] 2017-09-08 16:52
@CamiloTerevinto See #419 for latest comments on server side rendering.

**Comment by emoralesb05** [comment] 2017-10-11 16:56
Closing this since we already have other issues targeting SSR

**Closed** 2017-10-11 16:56 UTC
