### ISSUE TITLE
separate out code snippets

### ISSUE THREAD

**Issue by ilsiepotamus** [Teradata/covalent#155] opened 2016-11-18 16:30 UTC
#### Feature Request

Abstract out all code snippets/examples into separate files that can then be transpiled or inlined into code.

#### What is the motivation / use case for changing the behavior?

This would allow code snippets to be unit tested, plunkr'd, and easily modified when breaking changes happen.

**Comment by jeremysmartt** [comment] 2018-09-06 17:44
close as duplicate of #1164

**Closed by jeremysmartt** 2018-09-06 17:44 UTC
Labels: Close Possible
