### ISSUE TITLE
Feature Request: tdChips bind ngModel to property

### ISSUE THREAD

**Issue by zyarnold** [Teradata/covalent#699] opened 2017-06-16 12:44 UTC
Use Case:
I have a tdchip element with the following chips
```
chipItems = [
    { name:"John Doe", age:24, address:"Gotham City" },
    { name:"Jane Da", age:25, address:"Gotham City" },
    { name:"Bruce Wayne", age:26, address:"Gotham City" }
]
```

The problem is I want to bind ngModel to "selectedPersons.names" instead of the whole person object

To sum it short I want "selectedPersons.names" to have a value of somewhat like this:
`[ "John Doe", "Bruce Wayne"]`

instead of this
```
[
   { name:"John Doe", age:24, address:"Gotham City" },
   { name:"Bruce Wayne", age:26, address:"Gotham City" }
]
```

**Comment by parker-mike** [comment] 2017-06-25 10:47
Though we can use a template for displaying the needed property like this:
` <ng-template td-chip let-chip="chip">
    {{chip.name}}
  </ng-template>`
we should have an interceptor for adding chips that will construct and return a proper object to be added to the array, otherwise only `requireMatch` will work, which is not that fancy...

**Comment by emoralesb05** [comment] 2017-06-27 21:43
Thats the actual point of `requireMatch`, to only allow selections via autocomplete, and not custom inputs. 

That being said, this can probably be linked to https://github.com/Teradata/covalent/issues/711

**Comment by icenold** [comment] 2017-06-27 23:26
```
Thats the actual point of requireMatch, to only allow selections via autocomplete, and not custom inputs.

That being said, this can probably be linked to #711

Plus maybe a compareWith input function so you can make that distinction yourself on how you map your model vs your items array.
```
I don't think you quite understand the use-case

**Comment by emoralesb05** [comment] 2017-06-27 23:30
Probably, elaborate a bit more then?

**Comment by emoralesb05** [comment] 2017-06-27 23:35
The reason i mentioned the other PR is because that one can be taken as an interceptor, when if you return `undefined`, it means "dont add it" (which is their use case` or you can parse it to any given format (which is this use case)

The compareWith is just so you can map the `items` array to the `model` array in any way on whats "selected"

**Comment by jeremysmartt** [comment] 2018-09-06 18:11
closing as duplicate of #711

**Closed by jeremysmartt** 2018-09-06 18:11 UTC
Labels: Close Possible
