### ISSUE TITLE
Update to material beta-11

### ISSUE THREAD

**Issue by jbthomps** [Teradata/covalent#892] opened 2017-09-29 15:31 UTC
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report
When trying to update my application to material beta-11, and enable compatibility mode to change my application to use the mat prefix over the md prefix, I cannot use teradata components that include md-components.  

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 4.3.3
Material 2.0.0-beta.11
Did this work in previous versions of Angular / Material?
This did work in previous material.

##### Other information

https://github.com/angular/material2/pull/6989/files points at a quick fix that the material team has used internally for the same problem without doing a full conversion.

Otherwise, an ETA on fully updating to beta.11 would be appreciated.

**Comment by aciccarello** [comment] 2017-09-29 15:55
Duplicate of #885 and #887 
A PR is in progress #890

Looking for existing issues before posting can save the Covalent team time so they can work on implementing features. :wink: Be sure to also search the closed issues.

**Comment by emoralesb05** [comment] 2017-10-03 15:11
https://github.com/Teradata/covalent/pull/890 has been merged, you can start testing if you install the `nightly-build`, and we are gonna release as soon as we do a last set of tests

**Closed by emoralesb05** 2017-10-03 15:11 UTC
