### ISSUE TITLE
Add chips object + autocomplete

### ISSUE THREAD

**Issue by denyshetzel** [Teradata/covalent#800] opened 2017-08-03 23:09 UTC
#### Bug Report

How to add new chip working with objects and autocomplete?
When I add a new chip, it does not appear as expected. I did not find a way to solve this.

![28908950-4e2a1694-77f4-11e7-9563-4c25328da9bf](https://user-images.githubusercontent.com/25107256/28947685-330ce784-787f-11e7-87e7-f5e30c6046aa.png)

More details on: http://plnkr.co/edit/iR7Pbq?p=preview

**Comment by jeremysmartt** [comment] 2018-09-05 23:08
plunker appears to be working?

**Comment by jeremysmartt** [comment] 2018-09-06 18:28
closing issue, plunker appears to be working, let us know if still an issue

**Closed by jeremysmartt** 2018-09-06 18:28 UTC
Labels: Close Possible

**Comment by denyshetzel** [comment] 2018-09-06 18:33
When I digit a value that don't exist in array of objects, I believed that the chip could transform the input in oject.

In the test when I digit XXXX the chip stay empty, but think I lack knowledge in the component.

![28947685-330ce784-787f-11e7-87e7-f5e30c6046aa](https://user-images.githubusercontent.com/25107256/45177718-b8252480-b1e1-11e8-8412-a33dda85db96.png)

Sorry for english.

**Comment by jeremysmartt** [comment] 2018-09-06 19:47
Ok, thanks, I think I see the issue you are describing.  Let me take a look and see.

**Comment by jeremysmartt** [comment] 2018-09-06 20:42
@denyshetzel Looks like your issue is you are missing the `requireMatch` on your td-chips.  So changing your plunker to:
```
<td-chips 
            [items]="filteredObjects"
            formControlName="cities"
            placeholder="Enter autocomplete strings"
            (inputChange)="filterObjects($event)"
            requireMatch>
```
should fix the issue

**Comment by denyshetzel** [comment] 2018-09-08 04:58
@jeremysmartt  With `requireMatch` enabled I can't enter a new value if I can't find it in the list. I thought somehow the td-chip could turn the value digited into a object into the td-chip, if it was a new value.

**Comment by jeremysmartt** [comment] 2018-09-10 15:51
@denyshetzel The issue is you are trying to use a mix of objects in strings.  So you are using:
```
objects: any[] = [
    {id: 1, name: 'San Diego'},
    {id: 2, name: 'San Franscisco'},
    {id: 3, name: 'Los Angeles'}
  ];
```

So if I change your plunk to:
```
<form [formGroup]="form" >
  <td-chips 
            [items]="filteredObjects"
            formControlName="cities"
            placeholder="Enter autocomplete strings"
            (inputChange)="filterObjects($event)">
    <ng-template td-chip let-chip="chip" >
      {{chip}}
    </ng-template>
    <ng-template td-autocomplete-option let-option="option">
      <div layout="row" layout-align="start center">
        {{option.name}}
      </div>
    </ng-template>
  </td-chips>
</form>
```
and
```
import {
  FormBuilder,FormGroup, NgForm, FormsModule, ReactiveFormsModule, Validators
} from '@angular/forms';
import {Component} from '@angular/core';
import {HttpInterceptorService} from '@covalent/http'
import {bootstrap} from '@angular/platform-browser-dynamic';
import { Response, Http } from '@angular/http';

export interface City{
  id:string;
  name:string;
}

@Component({
  selector: 'covalent-app',
  templateUrl: 'app.component.html'
})
export class AppComponent implements OnInit{

  form: FormGroup;

  objects: string[] = [
    'San Diego',
    'San Franscisco',
    'Los Angeles'
  ];
  
  filteredObjects: string[];

  objectsModel: string[] = this.objects.slice(0, 2);
  
  constructor(private _formBuilder: FormBuilder){
    this.createForm();
  }

  ngOnInit(){
    this.updateForm();
    //this.filterObjects('');
  }

  updateForm(){
    this.form.patchValue({
      cities:  ['Austin',
                'New York City'];
   });
  }

  createForm() {
    this.form = this._formBuilder.group({
      cities: [[], Validators.required]
   });
  }

  filterObjects(value: string): void {
    console.log('advv ' + value);
    this.filteredObjects = this.objects.filter((obj: any) => {
      if (value) {
        return obj.name.toLowerCase().indexOf(value.toLowerCase()) > -1;
      } else {
        return false;
      }
    }).filter((filteredObj: any) => {
      return this.objectsModel ? this.objectsModel.indexOf(filteredObj) < 0 : true;
    });
  }

  
}
```

Then it will work.  Notice I change your objects to string arrays and also changed the template to:
```
<ng-template td-chip let-chip="chip" >
      {{chip}}
    </ng-template>
```
instead of using `{{chip.name}}`

If you want to continue to use objects instead of strings then you would need to use the:
```
(add)="addEvent($event)"
```
And handle the difference between entering a string into the input box and storing objects in typescript
