### ISSUE TITLE
Improve Examples in Docs - Make it easy to use examples

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#244] opened 2017-01-09 23:16 UTC
Given that using code examples as is into projects is becoming a fashion, it would be a good idea to add multiple commonly used examples for all components along with the actual code.

An example would be to extend what is present in stepper and data-table docs to all components.

**Comment by emoralesb05** [comment] 2017-02-02 05:56
We did a first pass, but the main goal is to have proper demos with code that you can `copy + paste` and a plnkr demo of the component people can play around with it. 

This will probably have to be separated into smaller issues to attack each component separate.

**Comment by iceman3000** [comment] 2017-03-21 12:30
@asaph26 @emoralesb05 - I'm really struggling to use Covalent, every code example I've copied so far from the docs either throws errors or just plain out doesn't load. I've even been trying to copy examples from the very comprehensive demo app and its just not working. I am a pretty switched on programmer, I can't believe I'm just being a numpty, surely I must be missing something? Is there assumed knowledge about how Covalent works that I am missing?

I'm trying to make my app look like this screenshot: http://pasteboard.co/M4Uhxtf5W.png
(Card Over Layout with Fly-In Navigation Drawer)

When I copy the code in the example layout, I end up with this: http://pasteboard.co/M4V2B35Ra.png
- I was expecting the example to have Navigation like the other layout examples that come with navigation in the demos.
- I figured maybe this one needs a Navigation Drawer, so I look at those docs and add the td-navigation-drawer directive to the page only to find that nothing renderes and no errors are thrown.

I then thought well what if I just copy the example code from the Navigation Drawer page ( https://teradata.github.io/covalent/#/style-guide/navigation-drawer ) and see how it looks, still nothing loads.

Code: http://pasteboard.co/M54bp2Q8y.png
HTML: http://pasteboard.co/M55v4UHcM.png

I'm sorry to keep posting, I am just super keen to use Covalent but am growing increasingly frustrated with my experiences getting it to work "out of the box". It's just really frustrating me cause I feel like an idiot - the examples look so simple and are relatively well documented, but I just can't get them to work! Any help on this one would be greatly appreciated.

**Comment by kyleledbetter** [comment] 2017-03-21 14:06
In the world of node angular development there is little copy and paste development left with all the thousands of node dependencies, strict version dependencies, proper use of typescript etc. If you need copy and paste start with our quickstart and copy all the functional code from GitHub directly from demos. This applies to any angular, react, etc, repo. Much of the code in our docs does actually work if you have everything setup properly and you're copying and pasting from the demo tabs (don't just copy documentation code that actually list all the code options in the snippets). We follow docs style from angular-material and angular as a best practice. Obviously we can and will get better docs over time as we get more contributors but this isn't like copying and pasting bootstrap CSS code, it's much more complex by the nature and power of the angular 

Once you get a better handle of it we'd appreciate PRs showing how you'd documented it to make it easier

**Comment by istvanszoboszlai** [comment] 2017-03-21 17:53
@iceman3000, how familiar are you with Angular2 and bootstrapping Angular2 apps? Covalent cannot solve it for you unless you use the quickstart, and modify that code.
You indeed have to understand what you are copy-pasting. And sometimes you have to figure out dependencies when you use the examples in the covalent docs.
But I if you spend a few weeks with Angular, it will be easy. In the beginning it can be hard indeed.

**Comment by iceman3000** [comment] 2017-03-22 13:21
Thanks for your comments guys. After commenting I decided to do exactly that. I took the starter project and ripped everything out of it that I didn't want and copied my routes, services etc from the project I'd been playing with. So far I seem to have it working.

3 Examples of issues I've hit so far that I think should be corrected in the Docs, however not sure where to make those suggestion are as follows:

The use of broadcast in the demo seems to break as seen here:
https://github.com/Teradata/covalent/issues/425

The Data Tables Docs has a syntax error as seen here:
http://pasteboard.co/MuohmvVDe.png

The Data Table Example throws .length undefined (not sure why selectedRows is undefined, no docs on how to use or manipulate the selected rows data):
http://pasteboard.co/Mupkaq2tC.png

@kyleledbetter I absolutely love the project and would be happy to help however possible (although as stated, I'm not anguar2 wiz yet) - just let me know :) - I think the docs are quite nice and well laid out, just examples are proving hard to get working on a clean project. Maybe a step by step tutorial on constructing your own app from scratch explaining how to configure all the dependencies and structures etc. This is something I may even be able to do, but I'll need to get a little more familiar. I find when I'm learning something that reading docs is a struggle, I much prefer to just google "thing tutorial" and then learn from actual implementation. Because Covalent is so new, there is pretty much no mention on Google of anything outside of this Git Site.

@istvanszoboszlai This is my first time using TS and Angular2 - It's really really fresh, like within 2 weeks and I only code after work for a few hours at night.

**Comment by asaph26** [comment] 2017-03-22 14:10
@iceman3000 I think it is better if you can break your learning into understanding Angular and then focussing on using Covalent. Despite the fact that the documentation is not complete it is written with the assumption that people are comfortable with Angular at a basic level. 

**Selected Rows**
_This is a short tip. (Some version of this needs to be updated in the docs)_

Looking at your examples, the reason selectedRows is not defined is because you need to define it as an Array_(which has the length property associated with it)_. So in your component you need to do something like this.

 ```typescript
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { TdDataTableService, ITdDataTableColumn, ITdDataTableSelectEvent, ITdDataTableSelectAllEvent } from '@covalent/core';

@Component({
    selector: 'some-component',
    templateUrl: './some-component.component.html',
    styleUrls: ['./some-component.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SomeComponent {
    
    selectedRows: any[] = [];
    data: any[] = [];
    columns: any[] = [];

    constructor () {}

    //... All your code to generate the columns and data
}
```

The data table has a value Accessor attached to it (By this I mean it has a value property that can be accessed through ngModel. So you can have a two way data binding using the ngModel on the selectedRows property. Your template would look like this in that case. 

```html
<td-data-table [data]="data" [columns]="columns" [(ngModel)]="selectedRows" selectable="true"></td-data-table>
```

Everytime a row is selected, selectedRows contains the row. If there is a row already present in selectedRows, it is selected in the data table.

There are also other ways to handle the selected rows. You can listen to the `onRowSelect` and `onSelectAll` events and populate the selected Rows array

**Comment by jeremysmartt** [comment] 2018-09-06 17:47
duplicate of #1164

**Closed by jeremysmartt** 2018-09-06 17:47 UTC
Labels: Close Possible, docs, enhancement, epic
