### ISSUE TITLE
Custom Collection

### ISSUE THREAD

**Issue by nueko** [Teradata/covalent#1036] opened 2017-12-14 13:06 UTC
Hello, it is may be just a discussion/question.

What about creating collection,
something like [@feloy/angular-cli-collection](https://github.com/feloy/angular-cli-collection) and written [here ](https://blog.angularindepth.com/creating-your-own-application-template-for-angular-cli-95e22319cc24)?

**Comment by jotatoledo** [comment] 2017-12-14 14:25
- Use the issue template
- Explain yourself furthermore

**Comment by aciccarello** [comment] 2017-12-14 15:47
Are you talking about a starter project? For that https://github.com/Teradata/covalent-quickstart

**Comment by nueko** [comment] 2017-12-14 15:56
@aciccarello, something like that, but easier starter. something just like
```powershell
ng new --collection=@covalent/collection myapp --layout=dashboard
```

**Comment by aciccarello** [comment] 2018-01-16 18:45
Sounds like something that would work well as part of the new [covalent-tools project](https://github.com/Teradata/covalent-tools)

**Comment by jeremysmartt** [comment] 2018-09-05 23:33
I believe this is a duplicate of #1166

**Comment by jeremysmartt** [comment] 2018-09-06 18:39
closing as duplicate #1166

**Closed by jeremysmartt** 2018-09-06 18:39 UTC
Labels: Close Possible
